/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.dslperson.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslPersonScopeProvider extends DelegatingScopeProvider {
}
