/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.persondsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PersonDslStandaloneSetup extends PersonDslStandaloneSetupGenerated {

	public static void doSetup() {
		new PersonDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
