/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.persondsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.ppgti.persondsl.PersonDslRuntimeModule;
import org.ppgti.persondsl.PersonDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PersonDslIdeSetup extends PersonDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PersonDslRuntimeModule(), new PersonDslIdeModule()));
	}
	
}
