/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.dslperson;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslPersonRuntimeModule extends AbstractDslPersonRuntimeModule {
}
