/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.dslperson.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.ppgti.dslperson.parser.antlr.internal.InternalDslPersonParser;
import org.ppgti.dslperson.services.DslPersonGrammarAccess;

public class DslPersonParser extends AbstractAntlrParser {

	@Inject
	private DslPersonGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDslPersonParser createParser(XtextTokenStream stream) {
		return new InternalDslPersonParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Persons";
	}

	public DslPersonGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslPersonGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
