/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.dslperson.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DslPersonUiModule extends AbstractDslPersonUiModule {

	public DslPersonUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
