/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.dslperson.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.ppgti.dslperson.ui.internal.DslpersonActivator;

public class DslPersonUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslpersonActivator.getInstance().getInjector("org.ppgti.dslperson.DslPerson");
	}

}
