/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.persondsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PersonDslUiModule extends AbstractPersonDslUiModule {

	public PersonDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
