/*
 * generated by Xtext 2.25.0
 */
package org.ppgti.dslperson.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.ppgti.dslperson.DslPersonRuntimeModule;
import org.ppgti.dslperson.DslPersonStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DslPersonIdeSetup extends DslPersonStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DslPersonRuntimeModule(), new DslPersonIdeModule()));
	}
	
}
